server:
  port: ${PORT:8080}
spring:
  application:
    name:om-map
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/teachPlatform?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=false
    username: root
    password: 123456
  data:
    redis:
      host: localhost
      port: 6379
  mail:
    host: smtp.qq.com
    port: 465
    username: omlink@foxmail.com
    password: yzxlvgncghsjbdig
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
    debug: true
    protocol: smtp